# Generated by Django 5.2.8 on 2025-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appone',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
