# Generated by Django 5.2.8 on 2025-11-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_appone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appone',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
