# Generated by Django 5.2.8 on 2025-11-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_alter_chaireview_dateadded_chaicertificate_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='dateAdded',
            new_name='date_added',
        ),
    ]
