# Generated by Django 5.2.8 on 2025-11-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('NUR', 'Nursery'), ('KG', 'Kindergarten'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3')], max_length=3)),
                ('section', models.CharField(default='A', max_length=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.school')),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'ordering': ['school', 'grade', 'section'],
                'unique_together': {('school', 'grade', 'section')},
            },
        ),
    ]
