# Generated by Django 5.2.8 on 2025-12-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, 'Select Class'), ('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Four'), ('V', 'Fifth'), ('VI', 'Sixth'), ('VII', 'Seventh'), ('VIII', 'Eighth'), ('IX', 'Ninth'), ('X', 'Tenth')], max_length=4)),
                ('section', models.CharField(choices=[(None, 'Select Section'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
            options={
                'unique_together': {('name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('roll_no', models.PositiveIntegerField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.class_model')),
            ],
        ),
    ]
