# Generated by Django 5.2.8 on 2025-12-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
